title: State Officer, M.D.
email: matthew.jadud@gsa.gov
description: >-
  Pilot materials supporting CMS/SOs in using the Health Tracker.
baseurl: "" 

collections_dir: collections
collections:
  rubric:
    output: true
  courses:
    output: true
  pages:
    output: true
    permalink: /:name/

permalink: pretty

markdown: kramdown

exclude:
  - package.json
  - package-lock.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
  - degit.json
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock

# #################################################################
# #
# # Digital Analytics Program (DAP) configuration
# # HHS     - Department of Health and Human Services
# # GSA     - General Services Administration
# #
# #################################################################
# dap:
#   # agency: your-agency
#   # Optional
#   # subagency: your-subagency
# # Configuration for Google Analytics
# ga:
#   # ua: your-ua
