version: '3'
services:
  jekyll:
    image: jekyll/jekyll:4.0
    command: bundle exec jekyll serve --watch --incremental --host 0.0.0.0
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle